### ISSUE TITLE
"You don't have a kDrive yet!"

### ISSUE THREAD

**Issue by panasenco** [Infomaniak/android-kDrive#1017]
**Description**
Getting the message "You don't have a kDrive yet!" after logging in, despite having an active kDrive with files.

**Steps to reproduce**
1. Open Infomaniak kDrive
2. Log in
3. See message "You don't have a kDrive yet!" 

**Expected behavior**
Expecting to see the drive I already have

**Screenshots**
![Screenshot_20230706-003923](https://github.com/Infomaniak/android-kDrive/assets/5506411/9ad5684d-e718-4a47-b754-a8e8a89053e7)

![image](https://github.com/Infomaniak/android-kDrive/assets/5506411/8c8921ba-9325-4d40-a976-4b93b7ca4035)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S6 Active
 - Android version: 7.0
 - App version: 4.2.19

**Comment by JorisBodin** [comment]
Hello,

There is only one user on this drive and it's not "Aram Panasenco", it's the other one.
So if you connect with the user "Aram Panasenco", it's normal, he doesn't have a drive.

**Comment by panasenco** [comment]
Thanks, that cleared it up. I didn't realize the kDrive has separate users from the account.
