### ISSUE TITLE
Add option to store offline files in android local file structure

### ISSUE THREAD

**Issue by PatheticCode** [Infomaniak/android-kDrive#1046]
**Is your feature request related to a problem? Please describe.**
Some third party applications work on local files which should be synchronized with the cloud by kdrive (just as the windows and linux kdrive applications do). On android, the local files are stored in a cache instead of the local files and therefore can not be accessed from third party apps.
This is annoying because currently I need to manually download the current file, work on it and then upload it again. 

**Describe the solution you'd like**
Either add an option to sync local files or make the offline file available through the file system. 

**Describe alternatives you've considered**
This issue would also be solved by tracking local folders as requested here:
https://github.com/Infomaniak/android-kDrive/issues/682
So this ticket might be a duplicate.

**Additional context**
The best example is Keepass on my android phone. I would like to synchronize my password database between all my devices. It works well for Linux and windows, but the kdrive app stores the file in a database instead of the local files, therefore I can not access it from the keepass app.

**Comment by JorisBodin** [comment]
Offline files can be accessed by applications such as "keepass" (I use it myself ...).
Once the file has been modified by the application, it is automatically uploaded.

The file is located in the only place the application is allowed to save outside its private space: `Android/media/com.infomaniak.drive/offline_storage/userid/driveid/filename`

**Comment by PatheticCode** [comment]
Nice, thank you for the information. You might want to add it to the doku anywhere.
