### ISSUE TITLE
Zoom and pan in the pdf viewer are not centered with touch inputs 

### ISSUE THREAD

**Issue by mijorus** [Infomaniak/android-kDrive#1114]
*Note: Please write your issue only in english*

**Description**
When zooming a pdf document using the built in viewer, the zoom origin is always on the top left of the screen
**Steps to reproduce**
Open a pdf
Zoom with two fingers

**Smartphone (please complete the following information):**
 - Device: Nothing p1
 - Android version: 13

**Comment by sirambd** [comment]
We already know about this problem, and we're currently working on it.
As well as other features to simplify the use of pdf files from kDrive.

**Comment by tevincent** [comment]
It should be fixed in the upcoming 4.4.0 version. We completely revamped the PDF reader.
