### ISSUE TITLE
F-Droid missing changelog

### ISSUE THREAD

**Issue by scollovati** [Infomaniak/android-kDrive#1251]
**Description**
Currently the app changelog is not exposed to F-Droid website and app (See https://f-droid.org/en/packages/com.infomaniak.drive/). However it is possible and it is very useful for end users to check the new features and bug fixes. See this app for an example: https://f-droid.org/en/packages/com.nextcloud.client/

Useful info here: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#ways-of-providing-metadata

**Comment by KevinBoulongne** [comment]
I've added it for the v1.3.1.

It will be done for all next versions :)
