### ISSUE TITLE
Soucis de bouton sur Sony Xperia X compact

### ISSUE THREAD

**Issue by alxschilling** [Infomaniak/android-kDrive#126]
L'utilisateur remarque que les boutons systèmes sont masqués dans le thème blanc. Soucis côté OS ou de notre côté ?

![Screenshot-20210712-231049](https://user-images.githubusercontent.com/84569752/125934184-e4cccb84-1db6-44ed-8768-da86c3589423.png)
![Screenshot-20210712-231024](https://user-images.githubusercontent.com/84569752/125934186-28f4cba7-8f7b-4151-9c83-dde36ae3ec28.png)

**Comment by JorisBodin** [comment]
C'est l'application nextcloud
