### ISSUE TITLE
Can't complete auto picture sync

### ISSUE THREAD

**Issue by adrien-pedrina** [Infomaniak/android-kDrive#127]
Hello,

On the latest version of kDrive, 4.0.16, it is impossible to complete the configuration of the automatic photo backup.

Selecting the kDrive and the folder in it, ok, but the selection of the local folder sticks, kDrive does not see any folder to synchronize.

This blocks the whole configuration process.

Seen on a test device:

Wiko :) Sunny 
Android 10 
kDrive 4.0.16
User ID : 770559

And also other devices.

The rights have been given on the app for storage access so the problem does not come from there.

Thanks in advance

![Capture d-écrans_20210716-145824](https://user-images.githubusercontent.com/85635056/125953734-b9d075c6-1ff1-444e-a04e-0fc39b7e1be9.png)
![Capture d-écrans_20210716-145940](https://user-images.githubusercontent.com/85635056/125953737-5f4713bb-f7b6-4ea2-90e5-37869b2b96fb.png)

**Comment by sirambd** [comment]
This PR  https://github.com/Infomaniak/android-kDrive/pull/130 is a first fix.
We will see if https://github.com/Infomaniak/android-kDrive/pull/130 fix the problem here, otherwise we will have to investigate even more.

**Comment by Kilian-Perisset** [comment]
Apparently, it has been fixed by #130 .
I close this issue, feel free to reopen it if needed :)

**Comment by mmkostov** [comment]
4 years later I still have the same bug on s23 ultra.

**Comment by JorisBodin** [comment]
@mmkostov Please create a new issue to describe your problem exactly. Thank you
