### ISSUE TITLE
Create & edit URL files

### ISSUE THREAD

**Issue by KaKi87** [Infomaniak/android-kDrive#1371]
**Is your feature request related to a problem? Please describe.**
The Android kDrive app doesn't allow creating nor editing URL files.

**Describe the solution you'd like**
The ability for the Android kDrive app to allow creating and editing URL files like the web app does.

**Describe alternatives you've considered**
None

**Additional context**
The Android kDrive app already handles opening existing URL files, so being able to edit them and create new ones would be logical.

---
Thanks

**Comment by JorisBodin** [comment]
Hello,

If you share a url from a browser, it will create it in the app.

There are no plans to edit from the application.

**Comment by KaKi87** [comment]
Why ?
