### ISSUE TITLE
v2 - homepage

### ISSUE THREAD

**Issue by alxschilling** [Infomaniak/android-kDrive#144]
overlay de présentation : https://infomaniak.invisionapp.com/console/Application-mobile---kDrive-ckew6q4az1ejf01uxtyliabrt/ckrc4caps00cr01x86cwl08ix/play
paramètres : https://infomaniak.invisionapp.com/console/Application-mobile---kDrive-ckew6q4az1ejf01uxtyliabrt/ckfdvqb2t02e2010egajb60x4/play
page de personnalisation : https://infomaniak.invisionapp.com/console/Application-mobile---kDrive-ckew6q4az1ejf01uxtyliabrt/ckrc4caps00cs01x8ecs1heef/play

**Comment by flowbe** [comment]
We should also think of a system to prevent showing multiple floating panel at once
