### ISSUE TITLE
Soucis de choix de dossier à synchro

### ISSUE THREAD

**Issue by alxschilling** [Infomaniak/android-kDrive#146]

**Comment by alxschilling** [comment]
![image](https://user-images.githubusercontent.com/84569752/126802299-b7a4cb66-bd0b-48d2-9e67-432a4dc0c4ac.png)
![image](https://user-images.githubusercontent.com/84569752/126802329-4c6291a5-e1c3-45e4-b12c-8503698d40e6.png)


Bonjour,

J'ai un Samsung Galaxy S10+ sous Android 11 et je constate que la sauvegarde auto de mes photos ne fonctionne plus avec les dernières versions de votre app. (Nouvelle interface).
Et ce depuis le 15 juillet environ.
Les paramètres semblent justes (voir captures) mais je ne peux pas choisir le dossier qui contient mes photos faites par l'appareil.
Uniquement le dossier download et ceux de Telegram et WhatsApp.
😢
Merci de votre aide.

Christian.

**Comment by Christian1217** [comment]
Je tiens à ajouter que mes photos de l'appareil sont sauvegardées sur la carte SD sous le répertoire "**/DCIM/Camera**" et non pas dans la mémoire de l'appareil.

Ça peut vous aider à trouver la cause ...

**Comment by JorisBodin** [comment]
Je viens de tester avec un Samsung Galaxy A51 + une carte SD, l'application trouve bien les dossiers présent dans la carte SD.
On continue l'investigation

**Comment by Christian1217** [comment]
Merci. Ce qui est étonnant en y réfléchissant c'est que l'app ne trouve pas non plus le dossier DCIM ou Camera de la mémoire du téléphone où il y a 2 ou 3 photos qui y traîne....

De plus, il faudrait qu'il puisse y avoir une option " sélectionner dossier " pu "parcourir" pour pouvoir le choisir à la main.

**Comment by JorisBodin** [comment]
Vous avez la dernière bien la dernière version ? (4.0.17)

**Comment by Christian1217** [comment]
Dans le doute j'ai supprimé l'app puis réinstallée.
Reconnexion et là il m'a demander l'autorisation pour l'accès à mes photos.
J'ai dit oui et dans les paramètres j'ai vu tous les répertoires que j'avais configuré avec l'ancienne app.
J'ai pris une photo et elle se sauvegarde maintenant.

Donc je pense que c'est les autorisations qui ont sauté quand j'ai mis à jour l'app de l'ancienne version la la nouvelle !

**Comment by JorisBodin** [comment]
C'est normalement les même autorisations que l'ancienne application (nextcloud) donc c'est très curieux
Merci pour votre retour :)

**Comment by Christian1217** [comment]
Merci pour votre travail ! 👍🏼
