### ISSUE TITLE
[Question] Where did the offline option go ?

### ISSUE THREAD

**Issue by KaKi87** [Infomaniak/android-kDrive#1506]
Hi,

I just now freshly installed kDrive from F-Droid on my Xiaomi Mi 8 running Android 14 and I can't find the option to make a directory available offline.

Where did it go ?

Thanks

**Comment by JorisBodin** [comment]
Hello,

This option has never existed, but you can select all the files in a folder to switch them to offline.

Best regards

**Comment by KaKi87** [comment]
Oh, I indeed got confused. Thank you
