### ISSUE TITLE
Translation issues from German

### ISSUE THREAD

**Issue by Kilian-Perisset** [Infomaniak/android-kDrive#158]
In the German version you can see the direct translation from French. This may be nice, but inappropriate and confusing for such an application.

Provided by @ik-tjacobse

**Comment by Kilian-Perisset** [comment]
@ik-tjacobse Do you have the list of concerned strings ? If yes, what changes must be done (do you have the new translations ?)

**Comment by ik-tjacobse** [comment]
Unfortunately not, we should check the whole app with native german speakers.

**Comment by supaeasy** [comment]
Do you use weblate or another open/crowd sourced translation? Would be more than happy to contribute.

**Comment by Kilian-Perisset** [comment]
@supaeasy 

Hi, we currently use a closed system which exports strings on both platforms (Android and iOS). 
Your contribution would be great, but I don't know if it's technically possible.

@JorisBodin What do you think?

**Comment by JorisBodin** [comment]
The problem with solutions like transiflex. It is that we don't have the translations quickly for a production launch.
And from experience, they are not necessarily better.

**Comment by supaeasy** [comment]
Ok. Please Ping me if you ever feel like opening this process.
