### ISSUE TITLE
Instant Upload does not work anymore

### ISSUE THREAD

**Issue by ik-tjacobse** [Infomaniak/android-kDrive#170]
Depuis la mise à jour du 6 août 2021, l'instant Upload ne fonctionne plus. J'ai essayé ajouter manuellement avec l'option "Importer depuis ce téléphone", cela rame et rame, cela dit que l'importation est en cours, mais cela ne se fait plus... Que faire ?

Appareil : Samsung Galaxy S10+
Langue de l'appareil : Français
Code de la version de l'application : 40002201
Nom de la version de l'application : 4.0.22
Version d'Android : Android 11 (SDK 30)

Source : Google Play

**Comment by JorisBodin** [comment]
Avec si peu d'information nous ne pouvons malheureusement rien faire
En attente de plus d'infos
