### ISSUE TITLE
Third party app uploading files stuck

### ISSUE THREAD

**Issue by adrien-pedrina** [Infomaniak/android-kDrive#183]
Hello,

Retour d'un utilisateur de l'application FairMail, application qui semble particulièrement appréciée par notre clientèle : 

https://twitter.com/infomaniak/status/1369210927581650944

Problème, lors que l'utilisateur cherche à sauvegarder une pièce jointe au format PDF en passant par le gestionnaire de fichier natif android, il est impossible d'enregistrer quoi que ce soit sur le kDrive.

En effet, lors de l'enregistrement, une erreur apparait (vous trouverez en PJ une vidéo descriptive du problème).

Le partage de la pièce jointe en question vers le kDrive fonctionne, mais pas l'enregistrement depuis un gestionnaire de fichier externe (qui liste pourtant le kDrive et montre son arborescence).

Point important, le problème semble toucher plusieurs apps, c'est la raison de son report ici (cela ne se limite donc pas que à Fairmail), de plus, cela a été reproduit sur 3 téléphones différents : 

- Xiaomi Mi 10T Pro - Android 11 -kDrive 4.0.23

- Honor P30 Lite - Android 10 - kDrive 4.0.23

- Wiko Y51 - Android One/10  - kDrive  4.0.23

Une excellente journée à vous et mes remerciements.

----------

Hello,

Feedback from a user of the FairMail application, which seems to be particularly appreciated by our customers: 

https://twitter.com/infomaniak/status/1369210927581650944

Problem, when the user tries to save an attachment in PDF format using the native android file manager, it is impossible to save anything on the kDrive.

Indeed, when saving, an error appears (you will find in PJ a video describing the problem).

Sharing the attachment in question to the kDrive works, but not saving from an external file manager (which lists the kDrive and shows its tree structure).

Important point, the problem seems to affect several apps, that's why it's reported here (so it's not limited to Fairmail), moreover, it has been reproduced on 3 different phones: 

- Xiaomi Mi 10T Pro - Android 11 -kDrive 4.0.23

- Honor P30 Lite - Android 10 - kDrive 4.0.23

- Wiko Y51 - Android One/10 - kDrive 4.0.23

A great day to you and my thanks.

https://user-images.githubusercontent.com/85635056/129192680-1336aae3-382c-4d17-ab67-55633bff60f6.mp4

**Comment by JorisBodin** [comment]
Oui toutes les actions dans le fileprovider n'ont pas été implémenté, une issue existe déjà : https://github.com/Infomaniak/android-kDrive/issues/163

Donc peut importe l'application. Merci du retour, qui confirme que c'est utilisé.

En attendant il faut utiliser l'option "partager vers kDrive"

**Comment by JorisBodin** [comment]
Disponible dans la version 4.0.38 : https://github.com/Infomaniak/android-kDrive/pull/330
https://github.com/Infomaniak/android-kDrive/milestone/34?closed=1
