### ISSUE TITLE
Soucis plantage lors suppression

### ISSUE THREAD

**Issue by alxschilling** [Infomaniak/android-kDrive#188]
Bonjour, la nouvelle application a fière allure, mais elle plante à chaque fois que j'appuie sur "Supprimer" dans la fenêtre contextuelle pour supprimer les photos déjà téléchargées. Bien cordialement Stéphan

**Comment by Kilian-Perisset** [comment]
Quelques pistes :

https://stackoverflow.com/questions/64472765/java-lang-illegalargumentexception-all-requested-items-must-be-referenced-by-sp

https://stackoverflow.com/questions/56496769/how-to-request-file-deletion-in-android-q-for-not-owned-files

**Comment by JorisBodin** [comment]
C'est corrigé dans la dernière version

**Comment by JorisBodin** [comment]
C'est corrigé dans la dernière version
