### ISSUE TITLE
Unable to select a folder during upload

### ISSUE THREAD

**Issue by adrien-pedrina** [Infomaniak/android-kDrive#201]
Hello,

User feedback regarding the fact that it is impossible to select a folder when uploading a document. This happens systematically on the latest version:

Device : Pixel 4a 5G - Android 11

Here is a video of the issue : 

https://user-images.githubusercontent.com/85635056/130418482-e0c5ff03-5b26-4e45-8623-e166346d45e1.mp4

Thank you in advance for your feedback, if the problem has ever been replicated on another test device.

**Comment by Kilian-Perisset** [comment]
Hello,
It has been fixed here : https://github.com/Infomaniak/android-kDrive/pull/195

Will be available in 4.0.25 👍
