### ISSUE TITLE
Already selected target folder but upload button disabled

### ISSUE THREAD

**Issue by reneluria** [Infomaniak/android-kDrive#215]
**Description**
When sharing a copy of a file from another app with kDrive, all items are already pre-selected: drive and destination folder.
But upload button is disabled.
One has to select the folder again for the button to be clickable

**Steps to reproduce**
1. share a copy of a file from app
2. select kDrive as destination
3. see the button disabled

**Expected behavior**
If destination drive and folder are already selected from previous usage, upload button should be clickable

**Screenshots**
I made a screencast if needed, just ask it if you need it.

**Smartphone (please complete the following information):**
 - Pixel 3
 - Android 11 (security patch August 5th)
 - App version 4.0.26

**Comment by JorisBodin** [comment]
If you change the name, it also activates the button. 
We check it 
Thanks for the feedback
