### ISSUE TITLE
Scan document

### ISSUE THREAD

**Issue by JorisBodin** [Infomaniak/android-kDrive#228]

**Comment by deuxnids** [comment]
That would be really nice!
 I just switched from Dropbox to kDrive and I'm really missing this feature. Hope to be able to scan document (multiple pages) in the next release.

**Comment by JorisBodin** [comment]
Hello @deuxnids,
It's a very very long feature to implement, it would be like developing a full document scanning application. So it won't happen in the near future.

Nevertheless you can use a dedicated application like Adobe https://play.google.com/store/apps/details?id=com.adobe.scan.android where you can save your scan on kDrive.

On iOS we don't have the problem, because Apple offers a document scanning api.

**Comment by deuxnids** [comment]
Hello @JorisBodin,
Thanks for your reply. Unfortunately with adobe scan data are stored on the adobe cloud...

**Comment by JorisBodin** [comment]
Hello @deuxnids,

Is now available in last beta of kDrive (4.2.0 build 11)
We use genius scan sdk.
