### ISSUE TITLE
Unhandled exception around canvas drawing

### ISSUE THREAD

**Issue by Kilian-Perisset** [Infomaniak/android-kDrive#32]
**Stacktrace :** 
```
RuntimeException: Canvas: trying to draw too large(128545280bytes) bitmap.
```

**Steps to reproduce :** 
Unknown (it's in PreviewSliderFragment > PinchToZoomRecyclerView)

We need to try to reproduce the problem, here are some examples of things we can do : 
- Consult a BIG pdf
- Consult a bad-format picture (corrupt)

**Comment by JorisBodin** [comment]
Fix by https://github.com/Infomaniak/android-kDrive/pull/45
