### ISSUE TITLE
User feedback - Photo import and view optimisation 

### ISSUE THREAD

**Issue by alxschilling** [Infomaniak/android-kDrive#37]
Based on the recent user feedback, we will improve the Pictures management.
A new view is being created for better files management.

![image](https://user-images.githubusercontent.com/84569752/119630538-5385da00-be0f-11eb-94c8-6c8f5b951c5f.png)

**Comment by JorisBodin** [comment]
And for Android:
![image](https://user-images.githubusercontent.com/2796439/119631267-035b4780-be10-11eb-96a5-d4d6b9412a27.png)
