### ISSUE TITLE
Choosing sharing link permissions in "Sharing and Rights" doesn't work for files .txt, .pptx, .xlsx, .docx

### ISSUE THREAD

**Issue by FabianDevel** [Infomaniak/android-kDrive#431]
In FileShareDetailsFragment, choosing sharing permissions only works for image and pdf
It works for all files in FileDetailsInfoFragment though

 - [x] Delete the useless`let` SelectPermissionBottomSheetDialog:81
 - [x] Fix

**Comment by sirambd** [comment]
- SelectPermissionBottomSheetDialog:90
 - FileShareDetailsFragment:100
