### ISSUE TITLE
File preview display issue when changing theme

### ISSUE THREAD

**Issue by LunarX** [Infomaniak/android-kDrive#461]
**Description**
When previewing a file, changing between dark and light theme breaks the preview. Also note that the 'open with' button on the top right of the screen becomes kind of blurry (see screenshots). File type (image, pdf, docx, zip, ...) doesn't matter and orientation of the screen doesn't matter, everything is affected.

**Steps to reproduce**
1. Go anywhere where you can preview any file
2. Click on a file to open the preview screen
3. Open the quick settings panel of the phone
4. Change between dark and light theme (one time is enough)
5. Close the quick settings panel to go back to the file preview

**Expected behavior**
The file preview should still display the opened file.

**Screenshots**
Before changing theme:
<img width="472" alt="Capture d’écran 2022-01-21 à 15 37 57" src="https://user-images.githubusercontent.com/32095402/150545595-df5a88f6-068b-4c98-bb09-2cb19f54b5b7.png">

After changing theme:
<img width="472" alt="Capture d’écran 2022-01-21 à 15 35 28" src="https://user-images.githubusercontent.com/32095402/150545267-b9721914-1f57-400e-bf22-7471c6069bae.png">

**Smartphone:**
 - Device: Pixel 4
 - Android version: Android 12
 - App version: 4.1.0

**Comment by JorisBodin** [comment]
Fixed in https://github.com/Infomaniak/android-kDrive/pull/449
