### ISSUE TITLE
Swipe refresh spinning endlessly in images

### ISSUE THREAD

**Issue by LunarX** [Infomaniak/android-kDrive#510]
**Description**
When changing between dark and light theme while in Your profile > Images, images reload and the spinner at the top of the screen loads indefinitely.

**Steps to reproduce**
1. Go to your profile (very last bottom menu on the right)
2. Click on Images
3. Change between dark and light theme
4. See the spinner loading forever even after the images have finished loading

**Expected behavior**
Either the images should not reload at all because they were already loaded or at least the spinner should stop spinning when the files are displayed.

**Screenshots**
![Screenshot_1643885571](https://user-images.githubusercontent.com/32095402/152329069-e16d76fc-f9b7-47c5-9bc5-2ea088239016.png)

**Comment by KevinBoulongne** [comment]
Another way to reproduce the same bug:

- Go to your profile (very last bottom menu on the right)
- Click on Images
- Display the preview of an Image
- Go back to the Images
- Refresh
- See the spinner loading forever
