### ISSUE TITLE
Make multi selection remove the favorite status of files if all of them are already in your favorites

### ISSUE THREAD

**Issue by LunarX** [Infomaniak/android-kDrive#516]
If at least one file is not in favorite, put all files' status in the selection to favorite.

Also change the color of the star icon in the bottom sheet to match the action of the button:
Add to favorite -> Star should be gray
Remove from favorite -> Star should be yellow

**Comment by JorisBodin** [comment]
https://github.com/Infomaniak/android-kDrive/pull/541
