### ISSUE TITLE
Downloading a file generates a .zip bigger than the original file

### ISSUE THREAD

**Issue by ochaze** [Infomaniak/android-kDrive#570]
First of all when downloading a single file I'd expect to download the file directly rather than an archive.zip 
Then the archive.zip is bigger than the original .xlsx file so this is nin addition useless :)

**Comment by JorisBodin** [comment]
In multi selection it downloads necessarily a .zip, you must download the file directly from its own menu so that it is not in zip.

For the size we'll see with the back that takes care of it.
