### ISSUE TITLE
User feedback - issue

### ISSUE THREAD

**Issue by alxschilling** [Infomaniak/android-kDrive#60]
"Hi,
I think there is a bug in kDrive mobile application for Android 8.0.0.
When you slide the single images of a folder the "Add to favorite" button works only for the first image. To be able to press the button again, you must return to the thumbnail screen and re-enter single view.
"

**Comment by JorisBodin** [comment]
It is reproducible, we look

**Comment by JorisBodin** [comment]
It's fixed: https://github.com/Infomaniak/android-kDrive/commit/996d3bd1ebf885255f2a840026a3b976768ed312
