### ISSUE TITLE
user feedback - fichier xls

### ISSUE THREAD

**Issue by alxschilling** [Infomaniak/android-kDrive#61]
Bonjour,

Depuis la mise à jour de l’application, je ne peux plus lire mes onglets dans mon fichier excel. 

Bien cordialement.
![image](https://user-images.githubusercontent.com/84569752/121700862-97940280-cad0-11eb-9004-4bf2d2830805.png)

**Comment by JorisBodin** [comment]
C'est uniquement une preview du fichier excel généré par onlyoffice au format PDF. Donc c'est pour cette raison qu'il ne peut pas cliquer sur les onglets.
Il faut ouvrir le fichier directement avec onlyoffice, en cliquant sur le bouton d'édition
Ou ouvrir le fichier dans une application de type excel.
