### ISSUE TITLE
Login webview refreshes content after rotation

### ISSUE THREAD

**Issue by mmc20520** [Infomaniak/android-kDrive#620]
*Note: Please write your issue only in english*

**Description**
Login webview refreshes content after rotation. Therefore we need to manually restore web state when rotating

**Steps to reproduce**
Click login and randomly browse in the login page, rotate your device

**Expected behavior**
Web page should remain unchanged

**Screenshots**
Before rotation:

![pic13](https://user-images.githubusercontent.com/100833575/156759291-f48a6398-b27e-4874-bc4b-76d4edf25614.png)

After rotation

![pic14](https://user-images.githubusercontent.com/100833575/156759309-220e73c4-3fd8-4b20-8f9e-cc5d45b5f592.png)

**Smartphone (please complete the following information):**
 - Device: Android emulator
 - Android version: Android 10
 - App version: 4.0.42

**Comment by JorisBodin** [comment]
Will be corrected soon
See: https://github.com/Infomaniak/android-login/issues/4

**Comment by JorisBodin** [comment]
Will be available in 4.1.2: https://github.com/Infomaniak/android-kDrive/pull/661/
