### ISSUE TITLE
Delete files after upload

### ISSUE THREAD

**Issue by supaeasy** [Infomaniak/android-kDrive#64]
Please add back an option to automatically delete photos and videos in local storage after successful upload.  This function existed in the last major android app and I have missed it ever since. 
Ideally I would wish for an initial function to do a full sync of local and kdrive folder and, if verified, delete all local files. 

> same as iOS > pop up pour demander l'accord

**Comment by alxschilling** [comment]
Hi,

Indeed, this feature was available in the last version of the app and is not available for now.
We have experienced some issues with people losing all or part of their photos when using it.
Indeed, the function automatically deletes the files after they are uploaded; however, in some cases, an upload issue happened, files were deleted and lost.

For our v2, this "delete after upload" feature is in the roadmap but not ready, as we need to make sure it is as robust as It can be. As this new app is very new, we are currently working on fixing some bugs and improving the overall stability.
We will then proceed to optimise the app with features like this "delete after upload" function.
Many thanks for your support and patience,

The Infomaniak team
