### ISSUE TITLE
App mobile : partage par utilisateurs

### ISSUE THREAD

**Issue by cedricstocke** [Infomaniak/android-kDrive#767]
pour ajouter les mails sur l'app mobile, je suis obligé de cliquer à chaque fois sur la petit popup qui m'affiche mon mail avec le message "inviter par mail" ([Screenshot_20220426-130356_kDrive.jpg](https://trello.com/1/cards/6267d176d347e64da86a7dc9/attachments/6267d242c120bc656739d289/download/Screenshot_20220426-130356_kDrive.jpg) )
possible de faire comme sur la webapp ? quand on écrit un espace -> l'adresse est automatiquement ajoutée (et si le mail n'est pas valable, je ne peux pas ajouter d'espace)

**Comment by LunarX** [comment]
The bottom right "done" button on the keyboard already does this, it autocompletes with the first available proposition
