### ISSUE TITLE
wrong file type detection

### ISSUE THREAD

**Issue by Ketelek** [Infomaniak/android-kDrive#904]
**Description**
trying to open keepass file ( .kdbx) does not work anymore since last update of kdrive app

**Steps to reproduce**
1. Go to 'kdrive app 4.2.8
2. Click on OPEN WITH..
3. Select 'abc.kdbx' keepass file.
4. See error: not able to open PDF ! (PDF?)

It's not possible to select an app after click on OPEN WITH

**Expected behavior**
open .kdbx in KeepassDX app. since it's not a .pdf file

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Huawei P20 pro
 - Android version: Android EMUI 12.0.0 (Build 226
 - App version: kdrive 4.2.8 & KeePassDX 3.4.5

**Additional context**
before kdrive 4.2.8 everything works fine for several month an different mix of app versions of kdrive and KeePassDX.

**Comment by JorisBodin** [comment]
It is necessary to identify the application that has been set by default to open `.kdbx` files on your phone.

The "open with" feature has not been modified in 4.2.8 and not even in 4.2.7.
It was refactored in February 2022.
It's a system call and then it's Android that launches the right application.
https://github.com/Infomaniak/android-kDrive/blob/master/app/src/main/java/com/infomaniak/drive/utils/Utils.kt#L245

If it says `not able to open PDF`, it's probably a PDF reader application that's running.
And I think it's `google drive` that's open. I just tried it, android shows me a lot of apps and the first one is google drive. And I get exactly the same message if I select google drive.
But if I select `Keepass2Android` it works

To remove the default opening of google drive (or another app), you have to go in the `information` of the application, then `Open by default` and there select `delete default preferences`.

Personally I put my `.kdbx` file in offline availability, and I open it directly from the `Keepass2Android` application. This way it is automatically synchronized by kDrive at each modification.
`(android/media/com.infomaniak.drive/offline_storage/user_id/drive_id/...)`

Tell me if everything is good now for you

**Comment by Ketelek** [comment]
Hello Joris, Thank you very much for the detailed feedback. I really appreciate it. The Problem I have is that the pop-up of the available apps does not appear any more. This means after clicking on OPEN WITH, the error message 'no pdf' appears instantly, so I'm unfortunately not able to select an app any more. Greetings JuergenAm 24.10.22, 17:01 schrieb Joris Bodin ***@***.***>:

   
  It is necessary to identify the application that has been set by default to open .kdbx files on your phone. 
  The "open with" feature has not been modified in 4.2.8 and not even in 4.2.7. It was refactored in February 2022. It's a system call and then it's Android that launches the right application. https://github.com/Infomaniak/android-kDrive/blob/master/app/src/main/java/com/infomaniak/drive/utils/Utils.kt#L245 
  If it says not able to open PDF, it's probably a PDF reader application that's running. And I think it's google drive that's open. I just tried it, android shows me a lot of apps and the first one is google drive. And I get exactly the same message if I select google drive. But if I select Keepass2Android it works 
  To remove the default opening of google drive (or another app), you have to go in the information of the application, then Open by default and there select delete default preferences. 
  Personally I put my .kdbx file in offline availability, and I open it directly from the Keepass2Android application. This way it is automatically synchronized by kDrive at each modification. (android/media/com.infomaniak.drive/offline_storage/user_id/drive_id/...) 
  Tell me if everything is good now for you

**Comment by JorisBodin** [comment]
Did you try clicking on `Clear default preferences`?

Otherwise you will have to use my solution to open the file from your Keepass app
