### ISSUE TITLE
Should hide `Categories menu` when not authorised

### ISSUE THREAD

**Issue by KevinBoulongne** [Infomaniak/android-kDrive#915]
<img width="526" alt="image" src="https://user-images.githubusercontent.com/1788629/199677436-955f509e-526d-441d-ae2b-f9839b18e38e.png">

**Comment by KevinBoulongne** [comment]
<img width="526" alt="image" src="https://user-images.githubusercontent.com/1788629/199677498-768ea127-4ba9-49eb-ad50-d8cfdb623389.png">

**Comment by FabianDevel** [comment]
The categories container should not be hidden, as we can see category set on unauthorised folder if it exists
