### ISSUE TITLE
Application Kdrive non disponible sur Huawei AppGallery

### ISSUE THREAD

**Issue by alxschilling** [Infomaniak/android-kDrive#98]
Bonjour, j'ai un téléphone huawei p40 pro et je souhaiterais télécharger votre application. Elle n'est pas disponible sur Huawei AppGallery. Comment accéder à l'application sur mon huawei ?

**Comment by JorisBodin** [comment]
Huawei à refusé notre application pour des raisons géopolitiques ...

La meilleur solution est de l'installer depuis f-droid : https://f-droid.org/packages/com.infomaniak.drive/
